import Head from "next/head";
import Searching from "@/components/searching/Searching";
import Trending from "@/components/trending/Trending";
import { GetServerSideProps, NextPage } from "next";
import { wrapper } from "@/store";
import { initTrendingHandler } from "@/store/trending-actions";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>StackOverflow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Searching />
        <Trending />
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps((store) => async () => {
    try {
      await store.dispatch(initTrendingHandler());
      return { props: {} };
    } catch {
      return { props: {} };
    }
  });
